[package]
name = "random_scheduler"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
shared_heap = { path = "../../../../domain-lib/shared_heap" }
basic = { path = "../../../../domain-lib/basic" }
task_meta = { path = "../../../../domain-lib/task_meta" }
common_scheduler = { path = "../../../common_lib/common_scheduler" }
storage = { path = "../../../../domain-lib/storage", features = ["impl"] }