[domains]
members = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "sshadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "virtio_mmio_net",
    "virtio_mmio_input",
    "virtio_mmio_gpu",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "random_scheduler",
    "logger",
    "xlogger",
    "net_stack",
    "domainfs",
    "vfs2"
]

init_members = [
    "plic",
    "syscall",
    "task",
    "vfs",
    "buf_uart",
    "buf_input",
    "cache_blk",
    "goldfish",
    "null",
    "random",
    "shadow_blk",
    "uart16550",
    "virtio_mmio_block",
    "devfs",
    "fatfs",
    "pipefs",
    "ramfs",
    "sysfs",
    "procfs",
    "fifo_scheduler",
    "logger",
    "net_stack",
    "domainfs",
]

disk_members = [
    "sshadow_blk",
    "virtio_mmio_gpu",
    "virtio_mmio_input",
    "virtio_mmio_net",
    "random_scheduler",
    "xlogger",
    "vfs2",
]