[package]
name = "procfs"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
rref = { path = "../../../../domain-lib/rref" }
basic = { path = "../../../../domain-lib/basic" }

generic = { path = "../../../common_lib/generic" }
vfscore = { path = "../../../../rvfs-ref/vfscore-ref", package = "vfscore-ref", features = ["linux_error"] }
dynfs = { path = "../../../../rvfs-ref/dynfs-ref", package = "dynfs-ref" }
log = "0"