[package]
name = "gfifo_scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../domain-lib/malloc" }
corelib = { path = "../../../domain-lib/corelib" }
basic = { git = "https://github.com/os-module/domain-lib"  }
rref = { git = "https://github.com/os-module/domain-lib"  }
interface = { git = "https://github.com/os-module/domain-lib",  features = ["domain"]  }

fifo_scheduler = { path = "../../common/fifo_scheduler" }
