[package]
name = "net_stack"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
rref = { path = "../../../../domain-lib/rref" }
basic = { path = "../../../../domain-lib/basic" }


spin = "0"
lose-net-stack = { git = "https://github.com/os-module/lose-net-stack", branch = "new_feature", features = ["log"]}
log = "0"
downcast-rs = { version = "1.2.0", default-features = false }