[package]
name = "guart16550"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corelib = { path = "../../../domain-lib/corelib" }
basic = { git = "https://github.com/os-module/domain-lib"  }
rref = { git = "https://github.com/os-module/domain-lib"  }
interface = { git = "https://github.com/os-module/domain-lib",  features = ["domain"]  }
malloc = { path = "../../../domain-lib/malloc" }
uart16550 = { path = "../../drivers/uart16550" }