[package]
name = "guart16550"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corelib = { path = "../../../domain-lib/corelib" }
basic = { path = "../../../domain-lib/basic"  }
rref = { path = "../../../domain-lib/rref"  }
interface = { path = "../../../domain-lib/interface",  features = ["domain"]  }
malloc = { path = "../../../domain-lib/malloc" }
uart16550 = { path = "../../drivers/uart16550" }