[alias]
domain = "run -p domain --"

[target.riscv64]
rustflags = [
    "-Clink-arg=-T../../domain.ld",
    "-Clink-arg=-pie",
    "-A", "unused_imports",
]
linker = "riscv64-linux-gnu-gcc"


[profile.release]
lto = true
strip = true
opt-level = 3