[package]
name = "gvirtio_mmio_block"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../../domain-lib/malloc" }
corelib = { path = "../../../../domain-lib/corelib" }
basic = { path = "../../../../domain-lib/basic" }
shared_heap = { path = "../../../../domain-lib/shared_heap" }
interface = { path = "../../../../domain-lib/interface",  features = ["domain"]  }
storage = { path = "../../../../domain-lib/storage", features = ["impl"] }
virtio_mmio_block = { path = "../virtio_mmio_block" }


[features]
default = ["rust-unwind"]
rust-unwind = []
