[package]
name = "pipefs"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
shared_heap = { path = "../../../../domain-lib/shared_heap" }
basic = { path = "../../../../domain-lib/basic" }

vfscore = { path = "../../../../rvfs-ref/vfscore-ref", package = "vfscore-ref" , features = ["linux_error"] }
dynfs = { path = "../../../../rvfs-ref/dynfs-ref", package = "dynfs-ref" }
generic = { path = "../../../common_lib/generic" }
log = "0"