[build]
#target = "riscv64gc-unknown-none-elf"
target = "./riscv64.json"
[target.riscv64gc-unknown-none-elf]
rustflags = [
    # build/domain.ld
    "-Clink-arg=-T./domain.ld",
    # pie
    "-Clink-arg=-pie",
    # no dynamic linking
#    "-Clink-arg=--no-dynamic-linker",
#    "-Clink-arg=--gc-sections",
#    "-Clink-arg=--emit-relocs",
]
linker = "riscv64-linux-gnu-gcc"


[target.riscv64]
rustflags = [
    "-Clink-arg=-T./domain.ld",
    "-Clink-arg=-pie",
    "-A", "unused_imports"
]
linker = "riscv64-linux-gnu-gcc"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[profile.release]
#panic = "abort"
lto = true
strip = true
opt-level = "z"  # Optimize for size.