[package]
name = "gtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
corelib = { path = "../../../../domain-lib/corelib" }
malloc = { path = "../../../../domain-lib/malloc" }
basic = { path = "../../../../domain-lib/basic" }
rref = { path = "../../../../domain-lib/rref" }
interface = { path = "../../../../domain-lib/interface",  features = ["domain"]  }
storage = { path = "../../../../domain-lib/storage", features = ["impl"] }

task = { path = "../task" }

[features]
default = ["rust-unwind"]
rust-unwind = []
