[package]
name = "gxlogger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
malloc = { path = "../../../../domain-lib/malloc" }
corelib = { path = "../../../../domain-lib/corelib" }
basic = { path = "../../../../domain-lib/basic",  default-features = false  }
rref = { path = "../../../../domain-lib/rref" }
interface = { path = "../../../../domain-lib/interface",  features = ["domain"]  }
storage = { path = "../../../../domain-lib/storage", features = ["impl"] }
xlogger = { path = "../xlogger" }

[features]
default = ["rust-unwind"]
rust-unwind = []
