[package]
name = "xlogger"
version = "0.1.0"
edition = "2021"


[dependencies]
interface = { path = "../../../../domain-lib/interface" }
shared_heap = { path = "../../../../domain-lib/shared_heap" }
basic = { path = "../../../../domain-lib/basic",  default-features = false  }
log = "0"